//
//  Constants.swift
//  flutter_paytabs_bridge
//
//  Created by Mohamed Adly on 21/03/2021.
//

import Foundation

let pt_profile_id = "pt_profile_id"
let pt_client_key = "pt_client_key"
let pt_server_key = "pt_server_key"
let pt_screen_title = "pt_screen_title"
let pt_amount = "pt_amount"
let pt_currency_code = "pt_currency_code"
let pt_tokenise_type = "pt_tokenise_type"
let pt_token_format = "pt_token_format"
let pt_token = "pt_token"
let pt_transaction_reference = "pt_transaction_reference"
let pt_cart_id = "pt_cart_id"
let pt_cart_description = "pt_cart_description"
let pt_merchant_country_code = "pt_merchant_country_code"
let pt_samsung_pay_token = "pt_samsung_pay_token"
let pt_merchant_name = "pt_merchant_name"
let pt_merchant_id = "pt_merchant_id"
let pt_server_ip = "pt_server_ip"
let pt_hide_card_scanner = "pt_hide_card_scanner"
let pt_simplify_apple_pay_validation = "pt_simplify_apple_pay_validation"
let pt_link_billing_name = "pt_link_billing_name"

// Billing
let pt_billing_details = "pt_billing_details"
let pt_address_billing = "pt_address_billing"
let pt_name_billing = "pt_name_billing"
let pt_email_billing = "pt_email_billing"
let pt_phone_billing = "pt_phone_billing"
let pt_city_billing = "pt_city_billing"
let pt_state_billing = "pt_state_billing"
let pt_country_billing = "pt_country_billing"
let pt_zip_billing = "pt_zip_billing"
// Shipping
let pt_shipping_details = "pt_shipping_details"
let pt_address_shipping = "pt_address_shipping"
let pt_name_shipping = "pt_name_shipping"
let pt_email_shipping = "pt_email_shipping"
let pt_phone_shipping = "pt_phone_shipping"
let pt_city_shipping = "pt_city_shipping"
let pt_state_shipping = "pt_state_shipping"
let pt_country_shipping = "pt_country_shipping"
let pt_zip_shipping = "pt_zip_shipping"
// metadata
let pt_ios_theme = "pt_ios_theme"
let pt_color = "pt_color"
let pt_theme_light = "pt_theme_light"
let pt_language = "pt_language"
let pt_show_billing_info = "pt_show_billing_info"
let pt_show_shipping_info = "pt_show_shipping_info"
let pt_force_validate_shipping = "pt_force_validate_shipping"
let pt_ios_primary_color = "pt_ios_primary_color"
let pt_ios_primary_font_color = "pt_ios_primary_font_color"
let pt_ios_secondary_color = "pt_ios_secondary_color"
let pt_ios_secondary_font_color = "pt_ios_secondary_font_color"
let pt_ios_stroke_color = "pt_oios_stroke_color"
let pt_ios_button_color = "pt_ios_button_color"
let pt_ios_button_font_color = "pt_ios_button_font_color"
let pt_ios_title_font_color = "pt_ios_title_font_color"
let pt_ios_background_color = "pt_ios_background_color"
let pt_ios_placeholder_color = "pt_ios_placeholder_color"
let pt_ios_primary_font = "pt_ios_primary_font"
let pt_ios_secondary_font = "pt_ios_secondary_font"
let pt_ios_stroke_thinckness = "pt_ios_stroke_thinckness"
let pt_ios_inputs_corner_radius = "pt_ios_inputs_corner_radius"
let pt_ios_button_font = "pt_ios_button_font"
let pt_ios_title_font = "pt_ios_title_font"
let pt_ios_logo = "pt_ios_logo"
let pt_transaction_type = "pt_transaction_type"
let pt_apms = "pt_apms"
