workflows:
  publish-to-pubdev:
    name: Bump Version, Update Changelog and Publish to pub.dev
    max_build_duration: 45
    environment:
      groups:
        - pub_credentials
        - git
      vars:
        PUBDEV_ACCESS_TOKEN: $PUBDEV_ACCESS_TOKEN
        PUBDEV_REFRESH_TOKEN: $PUBDEV_REFRESH_TOKEN
        PUBDEV_TOKEN_EXPIRATION: $PUBDEV_TOKEN_EXPIRATION
        GIT_CREDENTIALS: $GIT_CREDENTIALS
        GitUserEmail: $Git_Mail
        GitUserName: $Git_User
      flutter: stable
    scripts:
      - name: Setup git credentials
        script: |
          git config --global user.email "$GitUserEmail"
          git config --global user.name "$GitUserName"

      - name: Read current version
        script: |
          CURRENT_VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: //')
          echo "Current version: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $CM_ENV

      - name: Bump version
        script: |
          CURRENT_VERSION=$CURRENT_VERSION
          # Increment patch version (e.g., 2.7.2 -> 2.7.3)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          echo "Bumping version from $CURRENT_VERSION to $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $CM_ENV

          # Update pubspec.yaml (escape special chars and use portable sed)
          sed -i.bak "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" pubspec.yaml
          rm -f pubspec.yaml.bak

      - name: Update CHANGELOG with bug fix
        script: |
          NEW_VERSION=$NEW_VERSION

          # Create new changelog entry with bug fix
          {
            echo "## $NEW_VERSION"
            echo ""
            echo "* Bug Fix"
            echo ""
          } > changelog_entry.txt

          # Prepend to CHANGELOG.md
          cat changelog_entry.txt CHANGELOG.md > CHANGELOG.md.tmp
          mv CHANGELOG.md.tmp CHANGELOG.md
          rm changelog_entry.txt

          # Verify the change
          head -5 CHANGELOG.md

      - name: Create release branch
        script: |
          NEW_VERSION=$NEW_VERSION
          git checkout -b "release_$NEW_VERSION"
          git add pubspec.yaml CHANGELOG.md
          git commit -m "Bump version to $NEW_VERSION and update CHANGELOG"
          git push "https://${GIT_CREDENTIALS#*://}" "release_$NEW_VERSION" --set-upstream 2>&1 | grep -v "${GIT_CREDENTIALS}" || true

      - name: Create and push git tag
        script: |
          NEW_VERSION=$NEW_VERSION
          git tag -a "v$NEW_VERSION" -m "Release version $NEW_VERSION"
          git push "https://${GIT_CREDENTIALS#*://}" "refs/tags/v$NEW_VERSION" 2>&1 | grep -v "${GIT_CREDENTIALS}" || true

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Verify package health
        script: |
          flutter pub global activate pana
          pana --no-warning

      - name: Publish to pub.dev
        script: |
          mkdir -p ~/.pub-cache

          # Set up credentials file
          cat > ~/.pub-cache/credentials.json << 'EOF'
          {
            "version": 1,
            "hosted": [{
              "url": "https://pub.dartlang.org",
              "credentialType": "oauth2",
              "accessToken": "PUBDEV_ACCESS_TOKEN_VALUE",
              "refreshToken": "PUBDEV_REFRESH_TOKEN_VALUE",
              "tokenExpiration": PUBDEV_TOKEN_EXPIRATION_VALUE
            }]
          }
          EOF

          # Replace placeholders with actual values
          sed -i.bak "s|PUBDEV_ACCESS_TOKEN_VALUE|$PUBDEV_ACCESS_TOKEN|g" ~/.pub-cache/credentials.json
          sed -i.bak "s|PUBDEV_REFRESH_TOKEN_VALUE|$PUBDEV_REFRESH_TOKEN|g" ~/.pub-cache/credentials.json
          sed -i.bak "s|PUBDEV_TOKEN_EXPIRATION_VALUE|$PUBDEV_TOKEN_EXPIRATION|g" ~/.pub-cache/credentials.json
          rm -f ~/.pub-cache/credentials.json.bak

          chmod 600 ~/.pub-cache/credentials.json

          # Debug: verify credentials file (without showing tokens)
          echo "Credentials file created successfully"
          ls -la ~/.pub-cache/credentials.json

          echo "Publishing to pub.dev..."
          flutter pub publish --force

    publishing:
      email:
        recipients:
          - mobile.devop@paytabs.com
        notify:
          success: true
          failure: true
