workflows:
  publish-to-pubdev:
    name: Bump Version, Update Changelog and Publish to pub.dev
    max_build_duration: 45
    environment:
      groups:
        - pub_credentials
        - git
      vars:
        GIT_CREDENTIALS: $GIT_CREDENTIALS
        GitUserEmail: $Git_Mail
        GitUserName: $Git_User
        PUB_DEV_CREDENTIALS: $PUB_DEV_CREDENTIALS
      flutter: stable
    scripts:
      - name: Setup git credentials
        script: |
          git config --global user.email "$GitUserEmail"
          git config --global user.name "$GitUserName"

      - name: Read current version
        script: |
          CURRENT_VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: //')
          echo "Current version: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $CM_ENV

      - name: Bump version
        script: |
          CURRENT_VERSION=$CURRENT_VERSION
          # Increment patch version (e.g., 2.7.2 -> 2.7.3)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          echo "Bumping version from $CURRENT_VERSION to $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $CM_ENV

          # Update pubspec.yaml (escape special chars and use portable sed)
          sed -i.bak "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" pubspec.yaml
          rm -f pubspec.yaml.bak

      - name: Update CHANGELOG with bug fix
        script: |
          NEW_VERSION=$NEW_VERSION
          echo "Updating CHANGELOG for version $NEW_VERSION"

          # Create temporary file with new changelog entry
          cat > /tmp/changelog_entry.txt << 'EOF'
          ## $NEW_VERSION

          * Bug Fix

          EOF

          # Replace $NEW_VERSION with actual version
          sed -i "s|\$NEW_VERSION|$NEW_VERSION|g" /tmp/changelog_entry.txt

          # Prepend new entry to CHANGELOG.md
          cat /tmp/changelog_entry.txt CHANGELOG.md > CHANGELOG.md.new
          mv CHANGELOG.md.new CHANGELOG.md
          rm /tmp/changelog_entry.txt

          echo "✓ CHANGELOG updated successfully"
          echo "First 10 lines of CHANGELOG:"
          head -10 CHANGELOG.md

      - name: Create release branch
        script: |
          NEW_VERSION=$NEW_VERSION
          echo "Creating release branch: release_$NEW_VERSION"

          git checkout -b "release_$NEW_VERSION"
          git add pubspec.yaml CHANGELOG.md
          git commit -m "Bump version to $NEW_VERSION and update CHANGELOG"

          # Push with proper authentication
          echo "Pushing release branch to GitHub..."
          git remote set-url origin "https://${GIT_CREDENTIALS}"
          git push -u origin "release_$NEW_VERSION"
          echo "✓ Successfully pushed release_$NEW_VERSION branch"

      - name: Create and push git tag
        script: |
          NEW_VERSION=$NEW_VERSION
          echo "Creating tag: v$NEW_VERSION"

          git tag -a "v$NEW_VERSION" -m "Release version $NEW_VERSION"

          # Push tag with authentication
          echo "Pushing tag to GitHub..."
          git remote set-url origin "https://${GIT_CREDENTIALS}"
          git push origin "v$NEW_VERSION"
          echo "✓ Successfully pushed tag v$NEW_VERSION"

      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Publish to pub.dev
        script: |
          echo $PUB_DEV_CREDENTIALS > "$FLUTTER_ROOT/.pub-cache/credentials.json"
          flutter pub publish --dry-run
          flutter pub publish -f
    publishing:
      email:
        recipients:
          - mobile.devop@paytabs.com
        notify:
          success: true
          failure: true
